name: ETL & Analytics CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  ci:
    name: ETL CI (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    defaults:
      run:
        shell: bash

    steps:
    # --------------------------------------------------
    # 1. Checkout source code
    # --------------------------------------------------
    - name: Checkout repository
      uses: actions/checkout@v4

    # --------------------------------------------------
    # 2. Setup Python
    # --------------------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # --------------------------------------------------
    # 3. Cache dependencies
    # --------------------------------------------------
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # --------------------------------------------------
    # 4. Install dependencies
    # --------------------------------------------------
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # --------------------------------------------------
    # 5. Static sanity check – imports
    # --------------------------------------------------
    - name: Validate core module imports
      run: |
        python - <<EOF
        import etl.extract
        import etl.validate
        import etl.transform
        import etl.load
        import orchestration.main
        print("Core ETL modules imported successfully.")
        EOF

    # --------------------------------------------------
    # 6. Unit tests – data quality & transformation
    # --------------------------------------------------
    - name: Run unit tests (DQ & Transform)
      run: |
        pytest tests/ -v

    # --------------------------------------------------
    # 7. Explicit Data Quality Gate check
    # --------------------------------------------------
    - name: Data Quality Gate validation
      run: |
        python - <<EOF
        from etl.validate import validate_network_kpi

        result = validate_network_kpi()
        if not result["passed"]:
            raise Exception(
                f"DATA QUALITY GATE FAILED: {result['errors']}"
            )
        print("Data Quality Gate passed.")
        EOF
    # --------------------------------------------------
    # 8. Explicit Data Quality Report Artefact
    # --------------------------------------------------
    - name: Generate Data Quality Report
      run: |
        python - <<EOF
        import json
        import pandas as pd
        from etl.validate import validate_network_kpi

        df = pd.read_csv("data/raw/fact_network_kpi.csv")

        dq_result = validate_network_kpi(
            df,
            grain_columns=["year_month", "site_key", "service_key"]
        )

        with open("dq_report.json", "w") as f:
            json.dump(dq_result, f, indent=2)

        print("DQ report generated.")
        EOF

    # --------------------------------------------------
    # 9. Logging check (auditability)
    # --------------------------------------------------
    - name: Validate logging is enabled
      run: |
        python - <<EOF
        import logging
        logger = logging.getLogger("etl")
        if not logger.handlers:
            raise Exception("Logging handlers are not configured.")
        logger.info("Logging check passed.")
        EOF

    # --------------------------------------------------
    # 10. ETL dry-run (scheduler simulation)
    # --------------------------------------------------
    - name: ETL dry run (no publish)
      run: |
        python orchestration/main.py --dry-run

    # --------------------------------------------------
    # 11. CI success marker
    # --------------------------------------------------
    - name: CI completed successfully
      run: echo "CI PASSED — ETL, Data Quality, and Logging validated."
